import Link from "next/link";

import React, { useState } from "react";
import axios from "axios";

const Home = () => {
  const [number, setNumber] = useState("");
  const getNumberFromUser = (event) => {
    setNumber(event.target.value);
  };
  const sendNumber = () => {
    alert(number);
  };

  // const getNumberFromAI = () => {
  //   axios
  //     .get("https://api.quotable.io/random")
  //     .then((response) => {
  //       console.log(response.data);
  //     })
  //     .catch((error) => {
  //       console.log(error);
  //     });
  // };

  const axios = require("axios");

  const getCompletionFromAI = () => {
    const GROQ_API_KEY =
      "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"; // Replace 'YOUR_GROQ_API_KEY' with your actual GROQ API key
    const requestData = {
      messages: [
        {
          role: "user",
          content:
            " just generate a integer number no string and you are an active ai game player which have to guess number which from 1 to 100 , which will be generated by human player and you will have 5 tries to guess the number , and human will tell you if your guess is higher or lower than the number. you can make a stragey of divdie and conquer rule . plz plz plz just geneate a number not strings",
        },
      ],
      model: "llama3-8b-8192",
    };

    axios
      .post("https://api.groq.com/openai/v1/chat/completions", requestData, {
        headers: {
          Authorization: `Bearer ${GROQ_API_KEY}`,
          "Content-Type": "application/json",
        },
      })
      .then((response) => {
        // console.log(response.data);
        const completion = response.data.choices[0].message.content;
        console.log(completion);
      })
      .catch((error) => {
        console.error("Error:", error);
      });
  };

  return (
    <div>
      <div className="flex justify-center mt-9 h-screen">
        <div className="text-center">
          <h1 className="text-6xl font-black  mb-8  underline hover:underline-offset-8">
            AI VS HUMAN
          </h1>

          <div className="flex flex-col justify-center text-center">
            <input
              onChange={getNumberFromUser}
              placeholder="Enter the Number from 1 - 100"
              type="number"
              value={number}
              className="border-2 border-gray-300 text-black rounded-md px-4 py-2 focus:outline-none focus:border-blue-500"
            />

            <button
              // onClick={sendNumber}
              onClick={getCompletionFromAI}
              className="  mt-5 bg-white text-black px-4 py-2 rounded-md hover:bg-gray-800 hover:text-white focus:outline-none focus:bg-gray-800"
            >
              Click me
            </button>
          </div>

          {/* <div className="mb-4">
            <Link href="/HumanGuess">
              <button className="bg-blue-500 text-white px-4 py-2 rounded mr-4">
                Human Guess
              </button>
            </Link>
            <Link href="/AIGuess">
              <button className="bg-blue-500 text-white px-4 py-2 rounded">
                AI Guess
              </button>
            </Link>
          </div> */}
        </div>
      </div>
    </div>
  );
};

export default Home;
